# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: symfony_app
    restart: always
    working_dir: /var/www/symfony
    network_mode: host
    volumes:
      - .:/var/www/symfony
    depends_on:
      - database
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DATABASE_URL: ${DATABASE_URL}

  database:
    image: mysql:9.0.1
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: always
#    network_mode: host
    ports:
      - "80:80"
#      - "587:587"
    volumes:
      - .:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:

#networks: