<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFKZluFT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFKZluFT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFKZluFT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFKZluFT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFKZluFT\App_KernelDevDebugContainer([
    'container.build_hash' => 'FKZluFT',
    'container.build_id' => '0af8aee6',
    'container.build_time' => 1727952679,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFKZluFT');
